### ISSUE TITLE
Crash in analysis

### ISSUE THREAD

**Issue by arnimarj** [Shoobx/mypy-zope#11]
Hi, and thanks for a wonderful plugin. We've started using it to check our codebase, and have stumbled upon an issue. When type-checking parts of the `pyrsistent` library this happened:
```
/home/arni/dohop/bug/test-mypy-zope/lib/python3.7/site-packages/pyrsistent/_field_common.py:192: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.720
Traceback (most recent call last):
  File "mypy/newsemanal/semanal.py", line 4550, in accept
  File "mypy/nodes.py", line 921, in accept__Node_glue
  File "mypy/nodes.py", line 922, in accept
  File "mypy/newsemanal/semanal.py", line 989, in visit_class_def__StatementVisitor_glue
  File "mypy/newsemanal/semanal.py", line 992, in visit_class_def
  File "mypy/newsemanal/semanal.py", line 1063, in analyze_class
  File "mypy/newsemanal/semanal.py", line 1072, in analyze_class_body_common
  File "mypy/newsemanal/semanal.py", line 1131, in apply_class_plugin_hooks
  File "/home/arni/dohop/bug/test-mypy-zope/lib/python3.7/site-packages/mypy_zope/plugin.py", line 287, in analyze_subinterface
    base_node = api.lookup_fully_qualified_or_none(base_name)
  File "mypy/newsemanal/semanal.py", line 4016, in lookup_fully_qualified_or_none
AssertionError: 
/home/arni/dohop/bug/test-mypy-zope/lib/python3.7/site-packages/pyrsistent/_field_common.py:192: : note: use --pdb to drop into pdb
```

This happened when running under Pyhton 3.7.4, and can be reproduced like so:

```shell
#!/bin/bash

set -e

cat <<EOM >mypy.ini
[mypy]
show_traceback = True
plugins = mypy_zope:plugin
EOM


python -m venv test-mypy-zope
./test-mypy-zope/bin/pip install mypy==0.720 pyrsistent==0.15.4 mypy-zope==0.2.0
./test-mypy-zope/bin/mypy --show-traceback --config mypy.ini bug.py
```

**Comment by arnimarj** [comment]
Here is a smaller test-case

```python
def foo(x):
    class klass(x):
        pass
```

**Comment by kedder** [comment]
@arnimarj, thanks for the simple test case. I've pushed the fix for that smaller test-case you've posted, but I can't test it with your initial repro instructions - I miss the `bug.py` file mentioned there. 

Can you test it with the current master branch of `mypy-zope` (or provide the `bug.py` file)?

**Comment by arnimarj** [comment]
Hi, sorry for the oversight. Here is bug.py:

```python
from pyrsistent._field_common import pvector_field
pvector_field(int)
```

The issue seems to be resolved in the latest `master` branch

**Comment by kedder** [comment]
Great! Closing. Will make a new release soon.
