### ISSUE TITLE
Quick question: regarding stubgen

### ISSUE THREAD

**Issue by jlee7737** [Shoobx/mypy-zope#8]
Hello,

Thanks for your work on adding typing on zope.interface. Although we haven't used your project directly, it's been a lot of help.

We've been trying to generate stubs for zope.interface, but we're having problems generating one for C extension ```_zope_interface_coptimizations.c```, with the following traceback:
```
Traceback (most recent call last):
  File "/home/user/tmp/_env/bin/stubgen", line 10, in <module>
    sys.exit(main())
  File "mypy/stubgen.py", line 1173, in main
  File "mypy/stubgen.py", line 1084, in generate_stubs
  File "mypy/stubgenc.py", line 51, in generate_stub_for_c_module
  File "mypy/stubgenc.py", line 268, in generate_c_type_stub
  File "mypy/stubgenc.py", line 153, in generate_c_function_stub
TypeError: str object expected
```

It's crashing trying to generate from docstring, we were wondering how you were able to generate the stub file.

Thanks again for taking time to read this.

**Comment by kedder** [comment]
Hi, sorry for such a late response.

First of all, mypy project guys (https://github.com/python/mypy) are probably more qualified to comment on stubgen misbehavior. In any case, I think don't really need anything from `_zope_interface_coptimizations.c` - it is implementation optimizations, and for stubs you only care about public interface of the package - that should be fully defined in python files.
